this one might work, no installer yet but menuing modules do work

diff --git a/bim b/bim
--- a/bim
+++ b/bim
@@ -33,7 +33,9 @@ selection (? for help) ---> "
 	declare -A REPLYHELP=${REPLYHELPSTR#*=}
 	REPLYDICT["q"]="exit"
 	REPLYDICT["r"]="break"
-	REPLYDICT["<"]="break"
+	REPLYHELP["r"]="Leave this Menu (return)"
+	REPLYHELP["q"]="Leave the Program (quit)"
+	REPLYHELP["?"]="This Help"
 	if [[ -n "${TOPIC}" ]]
 	then
 		echo 
@@ -45,21 +47,36 @@ selection (? for help) ---> "
 		if [[ -z "${item}" ]] 
 		then
 			# get all args except for the reply cmd 
-			ARGS=(${REPLY})
-			REPLY="${ARGS[0]}"
-			ARGS="${ARGS[@]:1}"
+			AREPLY=(${REPLY})
+			REPLY="${AREPLY[0]}"
+			ARGS="${AREPLY[@]:1}"
 			if [[ -n ${REPLYDICT["${REPLY}"]} ]]
 			then
-				${REPLYDICT["${REPLY}"]} "${ARGS[@]}" || echo "reply command failed, returncode $?"
+				if [[ -z "${ARGS}" ]]
+				then
+					${REPLYDICT["${REPLY}"]} || echo "reply command failed, returncode $?"
+				else
+					${REPLYDICT["${REPLY}"]} "${ARGS[@]}" || echo "reply command failed, returncode $?"
+				fi
 			fi
-			if [[ -n "${REPLY}" == ? ]]
+			# print the help here
+			if [[ "${REPLY}" = "?" ]]
 			then
-				echo Here should be some help
+				echo ""
+				echo "This is Help for Menu:    ${TOPIC}"
+				echo ""
+				echo "You might also use the following commands:"
+				echo ""
+				for opt in "${!REPLYHELP[@]}"
+				do
+					echo "${opt}	${REPLYHELP[${opt}]}"
+				done
 			fi
-		fi
-		if [[ -n ${MENU["${item}"]} ]]
-		then 
-			${MENU["${item}"]} "${@}"|| echo "menu command failed, returncode $?"
+		else
+			if [[ -n ${MENU["${item}"]} ]]
+			then 
+				${MENU["${item}"]} "${@}"|| echo "menu command failed, returncode $?"
+			fi
 		fi
 	done
 }
